- name: Update apt and install wireguard
  apt:
    pkg:
      - wireguard
    state: latest
    update_cache: true

- file:
    path: "/etc/wireguard/keys-{{vpn_name}}/"
    state: directory

- name: Check server's wireguard key file
  stat:
    path: "/etc/wireguard/keys-{{vpn_name}}/server.privkey"
  register: privkey_stat

- name: Generate server's wireguard key
  shell: "wg genkey | tee /etc/wireguard/keys-{{vpn_name}}/server.privkey | wg pubkey > /etc/wireguard/keys-{{vpn_name}}/server.pubkey"
  when: not privkey_stat.stat.exists

- command: "cat /etc/wireguard/keys-{{vpn_name}}/server.{{item}}"
  register: key_proc
  loop:
    - privkey
    - pubkey

- set_fact:
    wgserver_privkey: "{{key_proc['results'][0]['stdout']}}"
    wgserver_pubkey: "{{key_proc['results'][1]['stdout']}}"

- name: Generate server IP Address
  set_fact:
    wgserver_ip: "{{ subnet | ansible.utils.ipaddr('next_usable') }}/{{ subnet | ansible.utils.ipaddr('prefix') }}"
    wgserver_subnet: "{{ subnet | ansible.utils.ipaddr('net') }}"

- name: Generate the configuration file
  template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{vpn_name}}.conf"
  
- name: Generate backup configuration file
  template:
    src: wg0.conf.j2
    dest: "/etc/wireguard/{{vpn_name}}.back.conf"

- name: Enable the wireguard service
  systemd:
    name: "wg-quick@{{vpn_name}}"
    enabled: yes