"""extend server info

Revision ID: 5934db0dbd26
Revises: b90c23888c3f
Create Date: 2023-10-24 01:58:34.005153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5934db0dbd26'
down_revision = 'b90c23888c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_aws_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('instance_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index('service_idx')

    op.drop_table('services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('challenge_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='services_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='services_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='services_pkey'),
    sa.UniqueConstraint('address', name='services_address_key'),
    sa.UniqueConstraint('team_id', 'challenge_id', 'order', name='services_team_id_challenge_id_order_key')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index('service_idx', ['team_id', 'challenge_id'], unique=False)

    op.drop_table('server_aws_infos')
    # ### end Alembic commands ###
