---
- name: Setup and deploy Ailurus backend and keeper server
  hosts: backend
  become: true
  roles:
  - docker-install
  - surround-setup
  - backend-setup
  - caddy-setup
  - backend-run
  - caddy-add-directive