---
- name: Run worker Docker container
  docker_container:
    name: ailurus-worker-{{worker_id}}
    image: ailurus-backend:latest
    state: started
    restart_policy: always
    command: worker
    volumes:
    - "/opt/ailurus-worker/ailurus/worker_data:/opt/app/ailurus/worker_data"