credentials:
  aws_access_key_id: access_key
  aws_secret_access_key: secret_access_key
  region_name: us-east-1
templates:
  infra: vpc-samba-resource.json
  machine: team-resource.json
local_user:
  team: ubuntu
  checker: ctf

# Cloudformation Parameters
parameters:
  # global parameter
  EventSlug: Ailurus
  
  # vpc samba parameters
  CidrBlock: 10.0.32.0/20
  PublicCidrBlock: 10.0.47.0/24
  PrivateCidrBlock: 10.0.32.0/22
  SambaMachineAMI: ami-04a81a99f5ec58529 
  SambaPrivateIpAddress: 10.0.35.1
  SambaMachineType: c5a.large

  # team parameters
  MachineAMI: ami-083ac6de37d37a7f4
  MachineType: t2.small